# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

parallel-jobs = 1

[Photos]
enabled = true
app-name = "Photos"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Spotify]
enabled = true
app-name = "Spotify"
build-mode = "apk"
arch = "all"
version = "auto"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"

[Music-Extended]
enabled = true
app-name = "Music"
build-mode = "apk"
arch = "all"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
build-mode = "apk"
arch = "all"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Reddit-Extended]
enabled = true
app-name = "Reddit"
build-mode = "apk"
arch = "all"
version = "auto"
rv-brand = "ReVanced Extended"
patches-source = "anddea/revanced-patches"
cli-source = "j-hc/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[Lightroom]
enabled = true
build-mode = "apk"
arch = "all"
version = "auto"
app-name = "Lightroom"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom"
uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.adobe.lrmobile/"
