name: Trigger CI on ReVanced Patches Releases

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  check-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout update branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: version

      - name: Fetch latest tags from repos
        id: fetch_tags
        run: |
          curl -s https://api.github.com/repos/anddea/revanced-patches/releases/latest > release_anddea.json
          curl -s https://api.github.com/repos/revanced/revanced-patches/releases/latest > release_official.json

          echo "tag_anddea=$(jq -r .tag_name release_anddea.json)" >> $GITHUB_OUTPUT
          echo "tag_official=$(jq -r .tag_name release_official.json)" >> $GITHUB_OUTPUT

      - name: Initialize missing tag files and exit early if needed
        id: init_tags
        run: |
          if [ ! -f "last_tag_anddea" ] || [ ! -f "last_tag_official" ]; then
            echo "${{ steps.fetch_tags.outputs.tag_anddea }}" > last_tag_anddea
            echo "${{ steps.fetch_tags.outputs.tag_official }}" > last_tag_official
            echo "missing=true" >> $GITHUB_OUTPUT
          else
            echo "missing=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push initialized tag files
        if: steps.init_tags.outputs.missing == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: version
          skip_checkout: true
          file_pattern: last_tag_*
          commit_message: "Initialize tag tracking files"

      - name: Exit early if tags initialized
        if: steps.init_tags.outputs.missing == 'true'
        run: exit 0

      - name: Compare and update tag files
        id: compare
        run: |
          LAST_ANDDEA=$(cat last_tag_anddea)
          LAST_OFFICIAL=$(cat last_tag_official)

          NEW_ANDDEA="${{ steps.fetch_tags.outputs.tag_anddea }}"
          NEW_OFFICIAL="${{ steps.fetch_tags.outputs.tag_official }}"

          SHOULD_TRIGGER=0

          if [ "$NEW_ANDDEA" != "$LAST_ANDDEA" ]; then
            echo "$NEW_ANDDEA" > last_tag_anddea
            SHOULD_TRIGGER=1
          fi

          if [ "$NEW_OFFICIAL" != "$LAST_OFFICIAL" ]; then
            echo "$NEW_OFFICIAL" > last_tag_official
            SHOULD_TRIGGER=1
          fi

          echo "SHOULD_TRIGGER=$SHOULD_TRIGGER" >> $GITHUB_OUTPUT

      - name: Commit and push updated tag files
        if: steps.compare.outputs.SHOULD_TRIGGER == '1'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: version
          skip_checkout: true
          file_pattern: last_tag_*
          commit_message: "Update last release tags"

      - name: Trigger Build workflow if new releases found
        if: steps.compare.outputs.SHOULD_TRIGGER == '1'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          token: ${{ secrets.PAT_TRIGGER_WORKFLOW }}
