name: Trigger Build on Patch Update

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  check-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout update branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: version

      - name: Fetch latest tags from repos
        id: fetch_tags
        run: |
          curl -s https://api.github.com/repos/anddea/revanced-patches/releases/latest > release_anddea.json
          curl -s https://api.github.com/repos/revanced/revanced-patches/releases/latest > release_official.json

          echo "tag_anddea=$(jq -r .tag_name release_anddea.json)" >> $GITHUB_OUTPUT
          echo "tag_official=$(jq -r .tag_name release_official.json)" >> $GITHUB_OUTPUT

      - name: Initialize missing tag files
        id: init_tags
        run: |
          if [ ! -f "last_tag_anddea" ] || [ ! -f "last_tag_official" ]; then
            echo "${{ steps.fetch_tags.outputs.tag_anddea }}" > last_tag_anddea
            echo "${{ steps.fetch_tags.outputs.tag_official }}" > last_tag_official
            echo "missing=true" >> $GITHUB_OUTPUT
          else
            echo "missing=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push initialized tag files
        if: steps.init_tags.outputs.missing == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: version
          skip_checkout: true
          file_pattern: last_tag_*
          commit_message: "Initialize tag tracking files"

      - name: Compare and update tag files
        id: compare
        run: |
          read -r LAST_ANDDEA < last_tag_anddea
          read -r LAST_OFFICIAL < last_tag_official

          NEW_ANDDEA="${{ steps.fetch_tags.outputs.tag_anddea }}"
          NEW_OFFICIAL="${{ steps.fetch_tags.outputs.tag_official }}"

          if [ -z "$NEW_ANDDEA" ] || [ -z "$NEW_OFFICIAL" ]; then
            echo "One of the fetched tags is empty!"
            exit 1
          fi

          SHOULD_TRIGGER=0

          if [ "$(printf '%s\n' "$NEW_ANDDEA" "$LAST_ANDDEA" | sort -V | tail -n1)" != "$LAST_ANDDEA" ]; then
            echo "$NEW_ANDDEA" > last_tag_anddea
            SHOULD_TRIGGER=1
          fi

          if [ "$(printf '%s\n' "$NEW_OFFICIAL" "$LAST_OFFICIAL" | sort -V | tail -n1)" != "$LAST_OFFICIAL" ]; then
            echo "$NEW_OFFICIAL" > last_tag_official
            SHOULD_TRIGGER=1
          fi

          echo "Comparing $LAST_ANDDEA vs $NEW_ANDDEA"
          echo "Comparing $LAST_OFFICIAL vs $NEW_OFFICIAL"

          echo "SHOULD_TRIGGER=$SHOULD_TRIGGER" >> $GITHUB_OUTPUT
          echo "old_anddea=$LAST_ANDDEA" >> $GITHUB_OUTPUT
          echo "new_anddea=$NEW_ANDDEA" >> $GITHUB_OUTPUT
          echo "old_official=$LAST_OFFICIAL" >> $GITHUB_OUTPUT
          echo "new_official=$NEW_OFFICIAL" >> $GITHUB_OUTPUT

      - name: Commit and push updated tag files
        if: steps.compare.outputs.SHOULD_TRIGGER == '1'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: version
          skip_checkout: true
          file_pattern: last_tag_*
          commit_message: "Update last release tags"

      - name: Checkout main branch to update config
        if: steps.compare.outputs.SHOULD_TRIGGER == '1'
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Generate filtered config
        if: steps.compare.outputs.SHOULD_TRIGGER == '1'
        run: |
          cp config.toml config.updated.toml

          awk -v old_anddea="${{ steps.compare.outputs.old_anddea }}" \
              -v new_anddea="${{ steps.compare.outputs.new_anddea }}" \
              -v old_official="${{ steps.compare.outputs.old_official }}" \
              -v new_official="${{ steps.compare.outputs.new_official }}" '
            BEGIN {
              in_section = 0
              should_disable = 0
            }
            /^\[.*\]/ {
              section = $0
              in_section = 1
              should_disable = 0
              is_official = 0

              if (section ~ /\[.*-Anddea\]/) {
                if (new_anddea == old_anddea) {
                  should_disable = 1
                }
              }
            }
            /patches-source *= *"revanced\/revanced-patches"/ {
              is_official = 1
              if (new_official == old_official) {
                should_disable = 1
              }
            }
            {
              if (should_disable && $0 ~ /enabled *= *true/) {
                sub(/enabled *= *true/, "enabled = false")
              }
              print
            }
          ' config.updated.toml > config.tmp && mv config.tmp config.updated.toml

      - name: Commit updated config
        if: steps.compare.outputs.SHOULD_TRIGGER == '1'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "Update config.updated.toml for new patches"
          file_pattern: config.updated.toml

      - name: Trigger Build workflow if new releases found
        if: steps.compare.outputs.SHOULD_TRIGGER == '1'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          token: ${{ secrets.PAT_TRIGGER_WORKFLOW }}
