name: Trigger CI on ReVanced Patches Releases

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  check-and-update-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout update branch
        uses: actions/checkout@v3
        with:
          ref: update
          token: ${{ secrets.PAT_TRIGGER_WORKFLOW }}

      - name: Get latest release from anddea
        id: anddea
        run: |
          curl -s https://api.github.com/repos/anddea/revanced-patches/releases/latest > release_anddea.json
          tag=$(jq -r .tag_name release_anddea.json)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Get latest release from official revanced
        id: official
        run: |
          curl -s https://api.github.com/repos/revanced/revanced-patches/releases/latest > release_official.json
          tag=$(jq -r .tag_name release_official.json)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Ensure .ci directory exists
        run: mkdir -p .ci

      - name: Read previous tags if files exist
        id: read_prev
        run: |
          if [ -f ".ci/last_tag_anddea" ]; then
            echo "LAST_ANDDEA=$(cat .ci/last_tag_anddea)" >> $GITHUB_ENV
          else
            echo "LAST_ANDDEA=" >> $GITHUB_ENV
          fi

          if [ -f ".ci/last_tag_official" ]; then
            echo "LAST_OFFICIAL=$(cat .ci/last_tag_official)" >> $GITHUB_ENV
          else
            echo "LAST_OFFICIAL=" >> $GITHUB_ENV
          fi

      - name: Compare and update tags files
        id: compare
        run: |
          SHOULD_PUSH=0
          NEW_ANDDEA=${{ steps.anddea.outputs.tag }}
          NEW_OFFICIAL=${{ steps.official.outputs.tag }}

          echo "Previous anddea tag: $LAST_ANDDEA"
          echo "New anddea tag: $NEW_ANDDEA"
          echo "Previous official tag: $LAST_OFFICIAL"
          echo "New official tag: $NEW_OFFICIAL"

          if [ "$NEW_ANDDEA" != "$LAST_ANDDEA" ]; then
            echo "$NEW_ANDDEA" > .ci/last_tag_anddea
            SHOULD_PUSH=1
          fi

          if [ "$NEW_OFFICIAL" != "$LAST_OFFICIAL" ]; then
            echo "$NEW_OFFICIAL" > .ci/last_tag_official
            SHOULD_PUSH=1
          fi

          echo "SHOULD_PUSH=$SHOULD_PUSH" >> $GITHUB_OUTPUT

      - name: Commit and push updated tags
        if: steps.compare.outputs.SHOULD_PUSH == '1'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .ci/last_tag_anddea .ci/last_tag_official
          git commit -m "Update last release tags"
          git push origin update

        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TRIGGER_WORKFLOW }}

      - name: Trigger Build workflow if new tags
        if: steps.compare.outputs.SHOULD_PUSH == '1'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          token: ${{ secrets.PAT_TRIGGER_WORKFLOW }}
